#:schema node_modules/wrangler/config-schema.json
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"
name = "discordmembers"

[observability]
enabled = true

[triggers]
crons = ["0 * * * *"]

[[kv_namespaces]]
binding = "DISCORDMEMBERS"
id = "8916ab8ac63d4f20bce0adae06f8e839"
